on:
    workflow_dispatch:
    push:
        branches:
            udc
jobs:
    buildAndUpload:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
                path: nabu_kernel
                set-safe-directory: "nabu_kernel/KernelSU"
                submodules: true
            - name: build docker image
              run: docker build -t nabu_kernel nabu_kernel
            - name: pull newest KernelSU
              run: |
                cd nabu_kernel/KernelSU
                pwd
                git pull -f 
                ls 
                cd ../..
            - name: build kernel
              run: |
                
                docker run -v $(pwd)/nabu_kernel:/nabu_kernel -w/nabu_kernel nabu_kernel
            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: kernel
                path: nabu_kernel/CosmicFresh/Kernel.zip


        