on:
    workflow_dispatch:
      inputs:
        title:
          description: 'Action title'
          required: false
          type: string
    push:
        branches:
            udc
run-name: ${{inputs.title}}
jobs:
    buildAndUpload:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
                path: nabu_kernel
                set-safe-directory: "nabu_kernel/KernelSU"
                submodules: true
            - name: build docker image
              run: docker build -t nabu_kernel nabu_kernel
            - name: build kernel
              run: |
                docker run -v $(pwd)/nabu_kernel:/nabu_kernel -w/nabu_kernel nabu_kernel
            - name: generate Summary
              run: |
                cd nabu_kernel/KernelSU
                KSU_ver=$(expr 10000 + $(git rev-list --count HEAD) + 200)
                echo "# KernelSU version: ${KSU_ver}   " >> $GITHUB_STEP_SUMMARY
                echo "### Build  Date: $(date)   " >> $GITHUB_STEP_SUMMARY
                cd ../..
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: kernel
                path: nabu_kernel/CosmicFresh/Kernel.zip
                retention-days: 5
            # - name: Notify to telegram bot
            #   uses: appleboy/telegram-action@master
            #   with:
            #     token: ${{secrets.TELEGRAM_BOT_TOKEN}}
            #     to: ${{secrets.TELEGRAM_BOT_TO}}
            #     message_file: nabu_kernel/CosmicFresh/Kernel.zip
            #     message: ${{inputs.title}}


        
